sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
  - linux
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - RUST_BACKTRACE=1
    - LLVM_VERSION=3.9
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then . ./.travis/before_install.sh llvm; fi
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
cache:
  cargo: true
  directories:
    - $HOME/.cargo